/* eslint-disable camelcase */
/* eslint-disable import/prefer-default-export */

import firebase from 'firebase';
import {AppContents} from './types';

const discovered_by: string[] = [
  'A friend',
  'MLH',
  'Facebook',
  'Twitter',
  'Posters',
  'Instagram',
  'Snapchat',
  'Other',
];

const race = [
  'Black / African American',
  'Hispanic',
  'East Asian',
  'South Asian',
  'Middle Eastern',
  'Native American',
  'White / Caucasian',
  'Multiple ethnicity / Other',
  'Prefer not to say',
];

const yearOfStudy = [
  'First Year',
  'Second Year',
  'Third Year',
  'Fourth Year',
  'Fifth Year',
  'Sixth Year',
];

const relation = [
  'Parent',
  'Grandparent',
  'Sibling',
  'Partner',
  'Friend',
  'Guardian',
  'Other',
];

const cities = [
  'Hamilton',
  'Toronto',
  'Waterloo',
  'London',
  'Montreal',
  'Ottawa',
  'Mississauga',
  'Guelph',
  'Burlington',
  'Brampton',
  'Markham',
  'Milton',
  'Other',
];

const shirt_size = ['XS', 'S', 'M', 'L', 'XL'];

const degree = ['Bachelors', 'Masters', 'PhD'];

const gender = ['Male', 'Female', 'Other'];

const food = [
  'None',
  'Vegetarian',
  'Vegan',
  'Halal',
  'Gluten Free',
  'Kosher',
  'No Beef',
  'Lactose Intolerant',
  'Gluten Free',
];

const allUniversities1 = [
  'McMaster University',
  'University of Waterloo',
  'University of Toronto',
  'University of Western Ontario',
  'Ryerson University',
  'Queen’s University',
  'University of Guelph',
  'University of Ottawa',
  'University of Windsor',
  'University of Ontario Institute of Technology',
  'Algoma University',
  'York University',
  'Concordia University',
  'McGill University',
  'Carleton University',
  'Brock University',
  'University of British Columbia',
  'Lakehead University',
  'Laurentian University',
  'Nipissing University',
  'OCAD University',
  'Redeemer University College',
  'Trent University',
  'University of St. Michael’s College',
  'University of Sudbury',
  'University of Trinity College',
  'Victoria University',
  'Wilfrid Laurier University',
  'Vancouver Island University',
  'Royal Roads University',
  'Simon Fraser University',
  'Trinity Western University',
  'Thompson River University',
  'University of the Fraser Valley',
  'University of Northern British Columbia',
  'University of Victoria',
  'First Nations University of Canada',
  'University of Regina',
  'University of Saskatchewan',
  'Athabasca University',
  'University of Alberta',
  'University of Calgary',
  'University of Lethbridge',
  'MacEwan University',
  'Mount Royal University',
  'Brandon University',
  'University of Manitoba',
  'University of Winnipeg',
  'Canadian Mennonite University',
  'St. Paul’s College',
  'Université de Saint-Boniface',
  'Acadia University',
  'Cape Breton University',
  'Dalhousie University',
  'Mount Saint Vincent University',
  'NSCAD University',
  'Saint Mary’s University',
  'St. Francis Xavier University',
  'Université Sainte-Anne',
  'University of King’s College',
  'Mount Allison University',
  'St. Thomas University',
  'Université de Moncton',
  'University of New Brunswick',
  'Memorial University of Newfoundland',
  'BRITISH COLUMBIA',
  'British Columbia Institute of Technology',
  'Okanagan College',
  'Ashton College',
  'Brighton College',
  'Columbia College',
  'Camosun College',
  'Canadian College',
  'Capilano University',
  'Collège Éducacentre',
  'College of the New Caledonia',
  'College of the Rockies',
  'Douglas College',
  'Justice Institute of British Columbia',
  'Kwantlen Polytechnic University',
  'Langara College',
  'Native Education College',
  'Nicola Valley Institute of Technology',
  'North Island College',
  'Northern Lights College',
  'Northwest Community College',
  'Okanagan College',
  'Selkirk College',
  'Sprott Shaw College',
  'Vancouver Community College',
  'Vancouver Institute of Media Arts',
  'Winnipeg Technical College',
  'Assiniboine Community College',
  'University College of the North',
  'Red River College of Applied Arts, Science and Technology',
  'École technique et professionnelle, Université de Saint-Boniface',
  'Manitoba Institute of Trades and Technology',
  'New Brunswick College of Craft and Design',
  'New Brunswick Community College',
  'Maritime College of Forest Technology',
  'New Brunswick Bible Institute',
  'College of the North Atlantic',
  'Algonquin College',
  'Collège Boréal',
  'Cambrian College of Applied Arts and Technology',
  'Canadore College of Applied Arts and Technology',
  'Centennial College of Applied Arts and Technology',
  'La Cité collégiale',
  'Conestoga College Institute of Technology and Advanced Learning',
  'Confederation College of Applied Arts and Technology',
  'Durham College',
  'Fanshawe College of Applied Arts and Technology',
  'Fleming College',
  'George Brown College',
  'Georgian College of Applied Arts and Technology',
  'Humber College Institute of Technology & Advanced Learning University of Guelph, Kemptville Campus',
  'Lambton College of Applied Arts and Technology',
  'Loyalist College of Applied Arts and Technology',
  'The Michener Institute for Applied Health Sciences',
  'Mohawk College of Applied Arts and Technology',
  'Niagara College',
  'Northern College of Applied Arts and Technology',
  'St. Clair College of Applied Arts and Technology',
  'St. Lawrence College',
  'Sault College of Applied Arts and Technology',
  'Seneca College of Applied Arts and Technology',
  'Sheridan College Institute of Technology and Advanced Learning',
  'Aurora College',
  'Academy of Learning College',
  'Canadian Coast Guard College',
  'Gaelic College',
  'Kingston Bible College',
  'Nova Scotia Community College',
  'Nunavut Arctic College',
  'Holland College',
  'Maritime Christian College',
  'Collège Acadie Î.-P.-É.',
  'Cégep de l’Abitibi-Témiscamingue',
  'Collège Ahuntsic',
  'Collège André-Laurendeau',
  'Cégep de Baie-Comeau',
  'Cégep Beauce-Appalaches',
  'Collège de Bois-de-Boulogne',
  'Champlain Regional College',
  'Cégep de Chicoutimi',
  'Dawson College',
  'Vanier College',
  'Cégep de Victoriaville',
  'Cégep du Vieux Montréal',
  'Collège Bart',
  'Collège Jean-de-Brébeuf',
  'Collège Laflèche',
  'LaSalle College',
  'Marianopolis College',
  'Collège International Marie de France',
  'Collège Mérici',
  'O’Sullivan College of Montreal',
  'Collège O’Sullivan de Québec',
  'Collège Stanislas',
  'École de musique Vincent d’Indy',
  'National Circus School',
  'Séminaire de Sherbrooke',
  'Trebas Institute',
  'Bethany College',
  'Briercrest College and Seminary',
  'Carlton Trail Regional College',
  'Horizon College and Seminary',
  'College Mathieu',
  'Cumberland College',
  'Eston College',
  'Great Plains College',
  'Nipawin Bible College',
  'Northlands College',
  'North West Regional College',
  'Parkland College',
  'Saskatchewan Indian Institute of Technologies',
  'Saskatchewan Institute of Applied Sciences and Technology',
  'Southeast Regional College',
  'St Peter’s College',
  'Western Academy Broadcasting College',
  'Yukon College',
  'Other',
];

const majorsList = [
  'Accounting',
  'Animal Biology',
  'Animal Science',
  'Anthropology',
  'Applied Human Nutrition',
  'Art',
  'Art History',
  'Biochemistry',
  'Biodiversity',
  'Biology',
  'Biological and Medical Physics',
  'Biological and Pharmaceutical Chemistry',
  'Biological Engineering',
  'Biological Science',
  'Biomedical Engineering',
  'Biomedical Toxicology',
  'Bio-Medical Science',
  'Chemical Physics',
  'Chemistry',
  'Chemical Engineering',
  'Child Studies',
  'Civil Engineering',
  'Classical Studies',
  'Computer Engineering',
  'Computer Science',
  'Criminal Justice and Public Policy',
  'Ecology',
  'Economics',
  'Engineering Systems and Computing',
  'English',
  'Environment and Resource Management',
  'Environmental Engineering',
  'Environmental Sciences',
  'Equine Management',
  'European Studies',
  'Family Studies and Human Development',
  'Food, Agricultural and Resource Economics',
  'Food and Agricultural Business',
  'Food Industry Management',
  'Food Science',
  'French Studies/Études Françaises',
  'General (B.A.)',
  'Geography',
  'Health Science',
  'History',
  'Honours Agriculture',
  'Hospitality and Tourism Management ',
  'Human Kinetics',
  'International Development Studies',
  'Life Science',
  'Management',
  'Management Economics and Finance',
  'Marine & Freshwater Biology',
  'Marketing Management',
  'Mathematics',
  'Mechanical Engineering',
  'Mechatronics Engineering',
  'Medicine',
  'Materials Engineering',
  'Microbiology',
  'Molecular Biology & Genetics',
  'Music',
  'Nanoscience',
  'Neuroscience',
  'Nutrition',
  'Philosophy',
  'Physical Science',
  'Physics',
  'Plant Science',
  'Political Science',
  'Psychology',
  'Public Management',
  'Spanish & Hispanic Studies',
  'Sociology',
  'Software Engineering',
  'Theatre Studies',
  'Theoretical Physics',
  'Undeclared',
  'Other',
];

const numberOfHackathons = [
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10+',
];

const workshops = [
  'Node.js',
  'React/Vue.js',
  'Blockchain',
  'Machine Learning',
  'Android Development',
  'iOS Development',
  'Web Development',
  'Intro to AR/VR',
  'Game Development',
  'Intro to UI/UX Design',
  'Hardware Hacking',
  'Computer Vision with OpenCV',
  'Buzzwords',
];

const roles = [
  'Front-end',
  'Back-end',
  'iOS Development',
  'Android Development',
  'Game Development',
];

export const blankApplication: AppContents = {
  _: {
    index: 0,
    reviews: {
      assignedTo: [],
      scores: [],
    },
    status: 'in progress',
    time_initiated: firebase.firestore.Timestamp.fromDate(new Date()),
    time_submitted: firebase.firestore.Timestamp.fromDate(new Date()),
  },
  name: {
    first: '',
    last: '',
  },
  contact: {
    email: '',
    phone: '',
  },
  first_submitted: firebase.firestore.Timestamp.fromDate(new Date()),
  academics: {
    degree: '',
    major: '',
    graduating: firebase.firestore.Timestamp.fromDate(new Date()),
    school: '',
    year: '',
  },
  personal: {
    birthday: firebase.firestore.Timestamp.fromDate(new Date()),
    gender: '',
    race: '',
  },
  emergency: {
    name: '',
    phone: '',
    relation: '',
  },
  documents: {
    download_link: '',
    filename: '',
    id: '',
  },
  profiles: {
    devpost: '',
    github: '',
    linkedin: '',
    website: '',
    other: '',
  },
  responses: {
    anything_else: '',
    q1: '',
    q2: '',
    q3: '',
    workshops: [],
  },
  logistics: {
    discovered_by: '',
    diet_restrictions: '',
    shirt_size: '',
    traveling_from: '',
    hackathons_attended: 0,
    reimbursement: '',
    accomodations: '',
  },
  resume: {
    filename: '',
    link: '',
  },
  general: {
    coffee: '',
    team: '',
    terms: '',
    code: false,
  },
};

export const applicationQuestions: any = [
  {
    label: "What's your first name?",
    fieldType: 'text',
    model: ['name', 'first'],
    requirements: {required: true},
  },
  {
    label: 'And your last name?',
    fieldType: 'text',
    model: ['name', 'last'],
    requirements: {required: true},
  },
  {
    label: 'What number can we reach you at?',
    fieldType: 'text',
    model: ['contact', 'phone'],
  },
  {
    label: 'Where do you study?',
    fieldType: 'single-select',
    selectData: allUniversities1,
    icon: 'fa-school',
    model: ['academics', 'school'],
    requirements: {
      required: true,
      oneOf: allUniversities1,
    },
  },
  {
    label:
      'Are you currently enrolled or will be enrolled in a secondary program by January 25th, 2020?',
    fieldType: 'single-select',
    selectData: ['Yes', 'No'],
    model: ['academics', 'enrolled'],
    requirements: {required: true, mustBe: 'Yes'},
  },
  {
    label: 'What degree are you pursuing?',
    fieldType: 'single-select',
    selectData: degree,
    icon: 'fa-certificate',
    model: ['academics', 'degree'],
    requirements: {required: true, oneOf: degree},
  },
  {
    label: "What's your major?",
    fieldType: 'single-select',
    selectData: majorsList,
    icon: 'fa-pencil-alt',
    model: ['academics', 'major'],
    requirements: {required: true, oneOf: majorsList},
  },
  {
    label: 'What is your current year of study?',
    fieldType: 'single-select',
    selectData: yearOfStudy,
    icon: 'fa-calendar',
    model: ['academics', 'year'],
    requirements: {required: true, oneOf: yearOfStudy},
  },
  {
    label: 'And when do you expect to graduate?',
    fieldType: 'date-grad',
    model: ['academics', 'graduating'],
    // requirements: { required: true, },
  },
  {
    label: "What's your birthday?",
    fieldType: 'date',
    model: ['personal', 'birthday'],
    requirements: {required: true},
  },
  {
    label: 'Will you be 18 or older on January 25th, 2020?',
    fieldType: 'radio-select',
    selectData: ['Yes', 'No'],
    model: ['academics', 'oldEnough'],
    requirements: {required: true, mustBe: 'Yes'},
  },
  {
    label: "What's your gender?",
    fieldType: 'radio-select',
    selectData: gender,
    model: ['personal', 'gender'],
    requirements: {
      required: true,
      oneOf: gender,
    },
  },
  {
    label: 'Which ethnic background do you identify with?',
    fieldType: 'single-select',
    selectData: race,
    icon: 'fa-user-circle',
    model: ['personal', 'race'],
    requirements: {required: true},
  },
  {
    label: 'How many hackathons have you been to?',
    fieldType: 'single-select',
    selectData: numberOfHackathons,
    icon: 'fa-list-ol',
    model: ['logistics', 'hackathons_attended'],
    requirements: {required: true, oneOf: numberOfHackathons},
  },
  {
    label:
      'What does positive change mean to you? How do you see yourself \
    incorporating positive change into your experience at DeltaHacks?',
    fieldType: 'text-area',
    textLimit: '500',
    model: ['responses', 'q1'],
    requirements: {required: true, max: 500},
  },
  {
    label: 'Describe a time you had to teach a new skill to someone.',
    fieldType: 'text-area',
    textLimit: '500',
    model: ['responses', 'q2'],
    requirements: {required: true, max: 500},
  },
  {
    label:
      'If you were stranded on a deserted island, with no way to escape, \
     for a month, what 3 personal items would you want to have?',
    fieldType: 'text-area',
    textLimit: '750',
    model: ['responses', 'q3'],
    requirements: {required: true, max: 750},
  },
  {
    label:
      'Is there anything else you want to tell us? It could be anything at all!',
    fieldType: 'text-area',
    textLimit: 200,
    model: ['responses', 'anything_else'],
    requirements: {max: 500},
  },
  {
    label: "What's your GitHub?",
    fieldType: 'text',
    model: ['profiles', 'github'],
    requirements: {link: true},
  },
  {
    label: "What's your LinkedIn?",
    fieldType: 'text',
    model: ['profiles', 'linkedin'],
    requirements: {link: true},
  },
  {
    label: "What's your personal website?",
    fieldType: 'text',
    model: ['profiles', 'website'],
    requirements: {link: true},
  },
  {
    label: "What's your devpost?",
    fieldType: 'text',
    model: ['profiles', 'devpost'],
    requirements: {link: true},
  },
  {
    label: 'Link us to any other profiles you have',
    fieldType: 'text',
    model: ['profiles', 'other'],
  },
  {
    label: 'What workshops would you like to see at Deltahacks VI?',
    fieldType: 'multi-select',
    selectData: workshops,
    icon: 'fa-wrench',
    model: ['responses', 'workshops'],
  },
  {
    label: 'Would you like to be considered for a coffee chat?',
    fieldType: 'single-select',
    selectData: ['Yes', 'No'],
    icon: 'fa-coffee',
    model: ['general', 'coffee'],
  },
  {
    label: 'Where are you travelling from?',
    fieldType: 'single-select',
    selectData: cities,
    icon: 'fa-plane',
    model: ['logistics', 'traveling_from'],
    requirements: {required: true, oneOf: cities},
  },
  {
    label: 'Do you require travel reimbursements?',
    fieldType: 'single-select',
    selectData: ['Yes', 'No'],
    icon: 'fa-ticket-alt',
    model: ['logistics', 'reimbursement'],
  },
  {
    label: 'Do you have any dietary restrictions?',
    fieldType: 'combo-box',
    selectData: food,
    icon: 'fa-utensils',
    model: ['logistics', 'diet_restrictions'],
  },
  {
    label: 'Do you require any special accomodations?',
    fieldType: 'text',
    model: ['logistics', 'accomodations'],
  },
  {
    label: 'Please put in the name of an emergency contact',
    fieldType: 'text',
    model: ['emergency', 'name'],
  },
  {
    label: "What is your emergency contact's phone number?",
    fieldType: 'text',
    model: ['emergency', 'phone'],
  },
  {
    label: 'Which size shirt do you wear?',
    fieldType: 'single-select',
    selectData: shirt_size,
    icon: 'fa-tshirt',
    model: ['logistics', 'shirt_size'],
  },
  {
    label: 'Do you already have a team?',
    fieldType: 'single-select',
    selectData: ['Yes', 'No'],
    icon: 'fa-users',
    model: ['general', 'team'],
  },
  {
    label: 'What is your "role" when going to hackathons?',
    fieldType: 'single-select',
    selectData: roles,
    icon: 'fa-users',
    model: ['general', 'role'],
  },
  {
    label: 'Please upload your resumé',
    fieldType: 'file',
    model: ['general', 'role'],
  },
];

export const authorizations: any = [
  {
    label:
      'I have read and agree to the MLH Code of Conduct. I authorize you to share my application/registration information for event administration, ranking, MLH \
    administration, pre- and post-event informational e-mails, and occasional messages about hackathons in-line with the \
    <a href="https://mlh.io/privacy" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()">MLH Privacy Policy</a>. \
    I further agree to the terms both the MLH Contest Terms and Conditions and the MLH Privacy Policy',
    model: ['general', 'code'],
  },
];

export const months: string[] = [
  'January',
  'Febuary',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
export const years: number[] = [];
export const days: number[] = [];

for (let i = 2024; i >= 1980; i--) years.push(i);
for (let i = 0; i <= 31; i++) days.push(i);
